import {
  ElAlert as LutterAlert,
  ElAside as LutterAside,
  ElAutocomplete as LutterAutocomplete,
  ElAvatar as LutterAvatar,
  ElBacktop as LutterBacktop,
  ElBadge as LutterBadge,
  ElBreadcrumb as LutterBreadcrumb,
  ElBreadcrumbItem as LutterBreadcrumbItem,
  ElButton as LutterButton,
  ElButtonGroup as LutterButtonGroup,
  ElCard as LutterCard,
  ElCarousel as LutterCarousel,
  ElCarouselItem as LutterCarouselItem,
  ElCascader as LutterCascader,
  ElCheckbox as LutterCheckbox,
  ElCheckboxButton as LutterCheckboxButton,
  ElCheckboxGroup as LutterCheckboxGroup,
  ElCol as LutterCol,
  ElCollapse as LutterCollapse,
  ElCollapseItem as LutterCollapseItem,
  ElContainer as LutterContainer,
  ElDatePicker as LutterDatePicker,
  ElDialog as LutterDialog,
  ElDivider as LutterDivider,
  ElDrawer as LutterDrawer,
  ElDropdown as LutterDropdown,
  ElDropdownItem as LutterDropdownItem,
  ElDropdownMenu as LutterDropdownMenu,
  ElFooter as LutterFooter,
  ElForm as LutterForm,
  ElFormItem as LutterFormItem,
  ElHeader as LutterHeader,
  ElIcon as LutterIcon,
  ElImage as LutterImage,
  ElInput as LutterInput,
  ElInputNumber as LutterInputNumber,
  ElLink as LutterLink,
  ElMain as LutterMain,
  ElMenu as LutterMenu,
  ElMenuItem as LutterMenuItem,
  ElMenuItemGroup as LutterMenuItemGroup,
  ElOption as LutterOption,
  ElOptionGroup as LutterOptionGroup,
  ElPagination as LutterPagination,
  ElPopconfirm as LutterPopconfirm,
  ElPopover as LutterPopover,
  ElPopper as LutterPopper,
  ElProgress as LutterProgress,
  ElRadio as LutterRadio,
  ElRadioButton as LutterRadioButton,
  ElRadioGroup as LutterRadioGroup,
  ElRate as LutterRate,
  ElRow as LutterRow,
  ElSelect as LutterSelect,
  ElSlider as LutterSlider,
  ElStep as LutterStep,
  ElSteps as LutterSteps,
  ElSubMenu as LutterSubMenu,
  ElSwitch as LutterSwitch,
  ElTabPane as LutterTabPane,
  ElTable as LutterTable,
  ElTableColumn as LutterTableColumn,
  ElTabs as LutterTabs,
  ElTag as LutterTag,
  ElText as LutterText,
  ElTimePicker as LutterTimePicker,
  ElTimeSelect as LutterTimeSelect,
  ElTimeline as LutterTimeline,
  ElTimelineItem as LutterTimelineItem,
  ElTooltip as LutterTooltip,
  ElTransfer as LutterTransfer,
  ElTree as LutterTree,
  ElUpload as LutterUpload,
  ElScrollbar as LutterScrollbar,
} from "element-plus";

export default {
  LutterAlert,
  LutterAside,
  LutterAutocomplete,
  LutterAvatar,
  LutterBacktop,
  LutterBadge,
  LutterBreadcrumb,
  LutterBreadcrumbItem,
  LutterButton,
  LutterButtonGroup,
  LutterCard,
  LutterCarousel,
  LutterCarouselItem,
  LutterCascader,
  LutterCheckbox,
  LutterCheckboxButton,
  LutterCheckboxGroup,
  LutterCol,
  LutterCollapse,
  LutterCollapseItem,
  LutterContainer,
  LutterDatePicker,
  LutterDialog,
  LutterDivider,
  LutterDrawer,
  LutterDropdown,
  LutterDropdownItem,
  LutterDropdownMenu,
  LutterFooter,
  LutterForm,
  LutterFormItem,
  LutterHeader,
  LutterIcon,
  LutterImage,
  LutterInput,
  LutterInputNumber,
  LutterLink,
  LutterMain,
  LutterMenu,
  LutterMenuItem,
  LutterMenuItemGroup,
  LutterOption,
  LutterOptionGroup,
  LutterPagination,
  LutterPopconfirm,
  LutterPopover,
  LutterPopper,
  LutterProgress,
  LutterRadio,
  LutterRadioButton,
  LutterRadioGroup,
  LutterRate,
  LutterRow,
  LutterSelect,
  LutterSlider,
  LutterStep,
  LutterSteps,
  LutterSubMenu,
  LutterSwitch,
  LutterTabPane,
  LutterTable,
  LutterTableColumn,
  LutterTabs,
  LutterTag,
  LutterText,
  LutterTimePicker,
  LutterTimeSelect,
  LutterTimeline,
  LutterTimelineItem,
  LutterTooltip,
  LutterTransfer,
  LutterTree,
  LutterUpload,
  LutterScrollbar
};
